// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfthwxymvefhcljytnnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmdGh3eHltdmVmaGNsanl0bm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyNzEwMjEsImV4cCI6MjA4NDg0NzAyMX0.q1sQbRYhA2HB4ms4Hpb-RX2UmSLTlLGEWmQNjDC4ymg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});